next(sendError(400, "Bad request"))
next(sendError(401, "Unauthorized"))
next(sendError(403, "Forbidden"))
next(sendError(404, "Not found"))
next(sendError(405, "Method Not Allowed"))
next(sendError(408, "Request Timeout"))
next(sendError(409, "Conflict/Duplicate"))
next(sendError(413, "Payload Too Large"))
next(sendError(415, "Unsupported Media Type"))
next(sendError(422, "Unprocessable"))
next(sendError(500, "Server error"))